# Generated by Django 4.0.6 on 2022-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(help_text='please enter ur email', max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
